spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  data:
    mongodb:
      uri: mongodb://localhost:27017/ecommerce # MongoDB connection URI
      database: ecommerce                       # Database name
  application:
    name: ecommerce-app                         # Application name

server:
  port: 8081                                    # Port for the Spring Boot application

logging:
  level:
    root: info                                  # Log level for root
    org.springframework.data.mongodb: debug    # Log level for MongoDB queries


springdoc:
  swagger-ui:
    path: /swagger-ui-custom.html

cloudinary:
  cloud-name: djrxcaxbc
  api-key: 165721923489928
  api-secret: ZdzyHrMrhVNeh9vtxG09CBvP3Uw